# Práctica Clase 3

## Numpy

In [1]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [2]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?
#RESPUESTA = en este caso vemos un array unidimensional, que lo conocemos como vector.

#Caso (n,)
arreglos = np.array([1, 2, 3])
print(arreglos.shape)

(3,)


In [43]:
#Caso (n,1)
arreglo = np.array([[1], [2], [3]])
arreglo_reshape = np.array([1, 2, 3]).reshape((1,3))
print ("forma del arreglo original:", arreglo.shape)
print ("forma del arreglo despues del cambio:", arreglo_reshape.shape)

forma del arreglo original: (3, 1)
forma del arreglo despues del cambio: (1, 3)


In [44]:
#Caso (1,n)

arregloo = np.array([[1, 2, 3]])
arreglo_reshapee = np.array([1, 2, 3]).reshape((3,1))
print ("forma del arreglo original:", arregloo.shape)
print ("forma del arreglo despues del cambio:", arreglo_reshapee.shape)



forma del arreglo original: (1, 3)
forma del arreglo despues del cambio: (3, 1)


In [ ]:
#¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista?
#RESPUESTA = y bueno en caso contrario de que en un array si se pueda y en una lista no
#tenemos como por ejemplo algunas operaciones como reshape y la transoposicion.
#un Ejemplo:

array = np.array([[1, 2],[3,4]])
reshape_array = np.reshape(array,4)
transposicion = array.T
print("Matriz original:",)
print(array)
print("Matriz luego del cambio",)
print(reshape_array)
print("Matriz luego de la transposicion",)
print(transposicion)


In [ ]:
#¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista?
# RESPUESTA = El metodo len tambien podria servir para las dos funcionalidades.
#un Ejemplo:

lista = [10,20,30,40,50]
lista2 = np.array([60,70,80,90,100,999])
print(F"la longitud de la lista: {len(lista)}")
print(F"la longitud de la lista: {len(lista2)}")

#como ya sabemos el metodo len nos funciona para saber la longitud de cada variable independientemente si estamos usando una lista o un array.

In [ ]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [ ]:
arreglo = np.arange(8)
print(arreglo)

Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [ ]:
lista + 1

In [ ]:
arreglo = arreglo + 1

In [ ]:
arreglo

2. Elevar al cuadrado todos los elementos

In [ ]:
lista**2

In [ ]:
arreglo**2

3. Sumar todos los elementos

In [ ]:
print(arreglo.sum())
print(lista.sum())

In [ ]:
n = 0
for e in lista:
    n = n + e
print(n)

In [ ]:
arreglo.shape

In [ ]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [ ]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

In [ ]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

In [ ]:
a3 = a1 * a2
a3.shape

In [ ]:
a3

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [ ]:
#Escribir un arreglo con números enteros del 0 al 9. Pista: arange
z = np.arange(0, 10)
print(z)

In [ ]:
#Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace
arreglos1 = np.linspace(0,9, 100)
print(arreglos1)
print(len(arreglos1))

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [ ]:
arreglo2 = np.arange(10, 101)
mascara = arreglo2 % 3 == 0
print(arreglo2[mascara])



**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [3]:
ceros = np.zeros((5,10), dtype = int)
print(ceros)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [4]:
ceros[[1,3],:]=1
print(ceros)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]]


In [5]:
ceros[:,[3,7]]= 2
print(ceros)

[[0 0 0 2 0 0 0 2 0 0]
 [1 1 1 2 1 1 1 2 1 1]
 [0 0 0 2 0 0 0 2 0 0]
 [1 1 1 2 1 1 1 2 1 1]
 [0 0 0 2 0 0 0 2 0 0]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [ ]:
a = np.random.random((4,2,3)) * 100 + 100
a

In [ ]:
a = np.random.random((4,4))

In [ ]:
a

In [ ]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8) #recalcamos que en este ejercicio la conversion de 200 a int8 fallara en un futuro por su actualizacion

In [ ]:
a

In [ ]:
a.sum()

In [ ]:
a.std()# std se utiliza para calcular la desviasion estandar de un array

In [ ]:
a.sort(axis=1)#el elemento sort sirve especificamente para para ordenar los elementos de un array a lo largo de un eje especifico

In [ ]:
a

In [ ]:
a.sort(axis=0)
a

In [ ]:
a[1:3,0:3]

In [ ]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [ ]:
a = np.array([l])

In [ ]:
a.shape

In [ ]:
a.reshape(24)

In [ ]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

In [ ]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

In [ ]:
c = a * b 
print(c) 

In [ ]:
d = b * a 
print(d)